import styles from '../styles/Home.module.css';
import Layout from '../components/Layout';
import Image from 'next/image';

export default function Home() {
  return (
    <Layout pageTitle='Home Page'>
      <Image src="/profile.png" width={200} height={200} alt="profile" />
      <h1 className={styles['title-homepage']}>Welcome Dede</h1>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente quidem possimus iure esse? Possimus sunt in dolorem molestias blanditiis culpa ab, ipsa rem iusto nihil, dolore quibusdam vitae dolor facere natus, ut neque. Deleniti consectetur ipsum, iure et possimus accusantium, exercitationem reprehenderit neque error distinctio quisquam officia ea, provident cupiditate libero sit delectus omnis amet? Officiis quidem, nulla odit neque sequi sint doloremque impedit harum sunt. Adipisci inventore temporibus sit exercitationem harum veritatis repellat voluptas nemo. Iusto est illo, at expedita blanditiis vel officia illum repellat deleniti cupiditate, nihil atque, modi magnam voluptatem earum? Et repellendus qui saepe? Ut amet saepe cupiditate, ex impedit, architecto ratione facere, dignissimos vitae iusto aliquid magni commodi pariatur? Doloribus doloremque ullam, at eaque corrupti dicta nihil dolor, quidem repellendus quo impedit delectus eos. Eaque fugit eum ab iste nisi laudantium sed voluptas voluptate, ex officia rem sequi. Sed eius magni voluptatibus temporibus dicta vero, nihil asperiores molestiae, aliquid adipisci ad officia nostrum cumque nisi, culpa tenetur doloribus eum unde officiis quam. Eligendi, nulla ratione. Ab, dolorem. Et suscipit necessitatibus perferendis nihil ex totam fuga, deleniti impedit? Odit dolorum repudiandae doloribus earum totam, cumque a sed consequuntur neque in similique ullam error quo dolor sint velit sit officia deleniti ea. Debitis enim quidem eveniet, iure tenetur iste eos dolorum illum cumque porro unde maiores totam alias natus nulla voluptatibus fuga corporis placeat suscipit. Pariatur, nulla. Et quod magnam unde quibusdam repudiandae hic a explicabo, provident dignissimos, culpa qui. Aspernatur, nulla. Doloremque excepturi blanditiis, accusantium adipisci eos expedita nostrum veritatis assumenda voluptate temporibus dolorem atque. Iure itaque omnis in dicta deserunt quod perferendis, veniam exercitationem quae harum. Perspiciatis, molestias debitis quia ea magni fugiat quo accusantium ipsam soluta at voluptas saepe assumenda commodi eius libero explicabo alias laboriosam voluptatem numquam laudantium? A iusto accusamus cumque, suscipit accusantium in, ipsa numquam beatae labore quod nulla consequatur, tempora laudantium. Eum veniam temporibus ex. Dolor excepturi harum dicta eaque doloribus voluptatem repellendus officia, animi inventore ratione dolores! Laborum veniam dolorem illum totam quaerat deserunt excepturi ipsum nisi a blanditiis voluptas voluptate natus at quae facilis provident nulla nesciunt labore vitae non quam, laudantium repellendus fuga rerum? Veniam eligendi, eum dignissimos voluptates laudantium iste ullam vero veritatis ipsum accusamus alias velit illo totam repellat fugiat, harum rerum est tenetur quis sapiente eaque sed magni. Eaque accusamus fugiat reprehenderit deserunt neque, iure quisquam magnam ad aut atque illo inventore blanditiis. Vel!</p>
    </Layout>
  )
}
